import type { Metadata } from "next";
import Link from "next/link";
import { config } from "@/lib/env";

export const metadata: Metadata = {
  title: "Terms of Service & Disclaimer — Fight IQ",
  description:
    "Fight IQ is a test/demo tool, not a commercial product. No warranty, not professional coaching or medical advice.",
};

function Section({
  id,
  title,
  children,
}: {
  id: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section id={id} className="scroll-mt-24">
      <h2 className="display mb-3 text-xl text-foreground">{title}</h2>
      <div className="space-y-3 text-[15px] leading-relaxed text-muted">
        {children}
      </div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-14">
      <header className="mb-10">
        <p className="mb-2 text-xs font-medium uppercase tracking-[0.18em] text-accent">
          Please read before uploading
        </p>
        <h1 className="display text-4xl leading-tight sm:text-5xl">
          Terms of Service &amp; Disclaimer
        </h1>
        <p className="mt-3 text-sm text-muted">
          Version {config.termsVersion}
        </p>
      </header>

      {/* The four things a reader must not miss, stated before any prose. */}
      <div className="mb-12 rounded-lg border border-accent/40 bg-accent-soft p-6">
        <h2 className="display mb-4 text-lg text-foreground">
          The short version
        </h2>
        <ul className="space-y-2.5 text-[15px] leading-relaxed text-foreground">
          <li className="flex gap-3">
            <span aria-hidden className="text-accent">
              —
            </span>
            <span>
              This is an <strong>experimental test tool</strong>, not a product.
            </span>
          </li>
          <li className="flex gap-3">
            <span aria-hidden className="text-accent">
              —
            </span>
            <span>
              It is <strong>not run for profit</strong>. Nothing is for sale and
              no payment is ever taken.
            </span>
          </li>
          <li className="flex gap-3">
            <span aria-hidden className="text-accent">
              —
            </span>
            <span>
              The analysis is AI-generated and may be wrong. It is{" "}
              <strong>not coaching or medical advice</strong>.
            </span>
          </li>
          <li className="flex gap-3">
            <span aria-hidden className="text-accent">
              —
            </span>
            <span>
              Only upload footage you own or have the right to use. Everything
              here may be <strong>deleted at any time without notice</strong>.
            </span>
          </li>
        </ul>
      </div>

      <div className="space-y-10">
        <Section id="test-tool" title="1. This is a test tool, nothing more">
          <p>
            Fight IQ is an experimental proof of concept, built to explore
            whether AI vision models can produce useful combat sports film
            study. It is not a commercial product, not a service, and is not
            offered to the public as either.
          </p>
          <p>
            It is under active development and frequently broken. Features
            appear and disappear without warning. Treat anything you see here as
            a demo, not as software you can rely on.
          </p>
        </Section>

        <Section id="not-for-profit" title="2. Not offered for profit">
          <p>
            There is no payment, no subscription, no trial, no upsell, and no
            commercial transaction of any kind involved in using this tool. It
            is not monetized, directly or indirectly. Nothing you do here
            creates a customer relationship, and no money will ever be requested
            from you.
          </p>
        </Section>

        <Section
          id="no-warranty"
          title="3. No warranty, and not professional advice"
        >
          <p>
            The tool is provided <strong>&ldquo;as is&rdquo;</strong>, without
            warranty of any kind, express or implied. There is no guarantee that
            the analysis is accurate, complete, consistent, or useful.
          </p>
          <p>
            The output is generated by an AI model reading a handful of sampled
            video frames. It can misread technique, invent detail that is not in
            the footage, and produce confident-sounding conclusions that are
            simply wrong. Two runs on the same clip may disagree.
          </p>
          <p className="rounded-md border border-border bg-surface p-4 text-foreground">
            <strong>
              The analysis is for entertainment and educational exploration
              only. It is not professional coaching, medical, physiotherapy,
              nutritional, or injury-prevention advice.
            </strong>{" "}
            Do not use it to make training decisions, diagnose an injury, change
            your technique, or decide whether you are ready to compete. Consult
            a qualified coach for training decisions and a qualified medical
            professional for anything health-related. If the tool and your coach
            disagree, your coach is right.
          </p>
          <p>
            Combat sports carry an inherent risk of serious injury. Nothing
            here reduces that risk, and the drills suggested by the tool have
            not been reviewed by anyone qualified to prescribe them.
          </p>
        </Section>

        <Section id="content" title="4. Content ownership and your footage">
          <p>
            <strong>Only upload footage you own or have the right to use.</strong>{" "}
            You are responsible for confirming you have permission to submit any
            video, including permission from anyone else visible in it. Do not
            upload footage of people who have not agreed to be recorded and
            analyzed.
          </p>
          <p>
            <strong>YouTube links.</strong> When you provide a YouTube URL, the
            footage is fetched and processed transiently, for the sole purpose
            of generating your own analysis result. It is not republished, not
            made publicly available, not shared with other users, not used to
            train any model, and not repurposed for anything beyond producing
            your result. Frames extracted during processing are stored privately
            and are readable only by your account.
          </p>
          <p>
            You keep whatever rights you already had in your footage. Uploading
            grants no ownership and no licence beyond what is technically
            necessary to run the analysis and show you the result.
          </p>
          <p>
            If you believe content has been uploaded in violation of your
            rights, use the contact address below and it will be removed.
          </p>
        </Section>

        <Section id="availability" title="5. Availability and data deletion">
          <p>
            This is a test environment. The tool may be modified, taken offline,
            reset, or removed entirely at any time, without notice. Your
            uploads, extracted frames, and generated analyses may be{" "}
            <strong>deleted at any time without notice or backup</strong>.
          </p>
          <p>
            Keep your own copy of any footage that matters to you. Do not treat
            this as storage. There is no data-retention commitment, no uptime
            commitment, and no export guarantee.
          </p>
        </Section>

        <Section id="acceptable-use" title="6. Acceptable use">
          <p>
            Do not upload footage of minors, non-consensual recordings, real
            violence outside a consensual sporting context, or anything illegal.
            Do not use the tool to harass, evaluate, or make decisions about
            another person without their knowledge.
          </p>
        </Section>

        <Section id="liability" title="7. Limitation of liability">
          <p>
            To the fullest extent permitted by law, the operator of this test
            tool accepts no liability for any loss, injury, or damage arising
            from its use or from reliance on its output. Because the tool is
            provided free of charge as an experiment, you use it entirely at
            your own risk.
          </p>
        </Section>

        <Section id="contact" title="8. Contact and attribution">
          <p>
            Built as a personal proof of concept exploring AI vision models
            alongside MediaPipe pose estimation. Not affiliated
            with, endorsed by, or connected to any athletic commission,
            promotion, gym, or the operators of any video platform referenced by
            this tool.
          </p>
          <p className="rounded-md border border-border bg-surface p-4">
            {/* Placeholder — swap for a real address before sharing the link. */}
            Contact:{" "}
            <span className="font-mono text-foreground">
              [add-your-contact-email@example.com]
            </span>
            <br />
            <span className="text-sm">
              Takedown requests and bug reports both go here.
            </span>
          </p>
        </Section>
      </div>

      <div className="mt-14 flex flex-wrap items-center gap-4 border-t border-border pt-8">
        <Link
          href="/upload"
          className="rounded-md bg-accent px-4 py-2 text-sm font-medium text-white transition-opacity hover:opacity-90"
        >
          Back to the app
        </Link>
        <p className="text-sm text-muted">
          You will be asked to acknowledge these terms before your first upload.
        </p>
      </div>
    </div>
  );
}
