import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { AnalysisView } from "@/components/AnalysisView";
import { createClient } from "@/lib/supabase/server";
import {
  JOB_STAGE_LABELS,
  isJobActive,
  type Analysis,
  type AnalysisJob,
  type Video,
} from "@/lib/types";

export const dynamic = "force-dynamic";

export const metadata: Metadata = { title: "Analysis — Fight IQ" };

export default async function AnalysisPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  // `id` is the video id — one analysis per video, so the video is the stable
  // permalink whether or not the analysis exists yet.
  const { id } = await params;
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) redirect(`/login?next=/analyses/${id}`);

  const { data: video } = await supabase
    .from("videos")
    .select("*")
    .eq("id", id)
    .maybeSingle<Video>();

  if (!video) notFound();

  // Cached result — reading it never triggers reprocessing.
  const { data: analysis } = await supabase
    .from("analyses")
    .select("*")
    .eq("video_id", id)
    .maybeSingle<Analysis>();

  const { data: job } = await supabase
    .from("analysis_jobs")
    .select("*")
    .eq("video_id", id)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle<AnalysisJob>();

  return (
    <div className="mx-auto max-w-3xl px-6 py-14">
      <header className="mb-10">
        <Link
          href="/analyses"
          className="mb-4 inline-block text-sm text-muted transition-colors hover:text-foreground"
        >
          ← My clips
        </Link>
        <h1 className="display text-4xl leading-tight">{video.title}</h1>
        <p className="mt-2 text-sm text-muted">
          {video.source === "youtube" ? "YouTube" : "Upload"} ·{" "}
          {new Date(video.created_at).toLocaleString()}
          {video.source === "youtube" && video.source_url ? (
            <>
              {" · "}
              <a
                href={video.source_url}
                target="_blank"
                rel="noopener noreferrer"
                className="underline underline-offset-4"
              >
                source
              </a>
            </>
          ) : null}
        </p>
        {video.notes ? (
          <p className="mt-3 rounded-md border border-border bg-surface px-4 py-3 text-sm text-muted">
            <span className="text-foreground">Your notes:</span> {video.notes}
          </p>
        ) : null}
      </header>

      {analysis ? (
        <>
          <AnalysisView analysis={analysis} video={video} />
          <p className="mt-10 rounded-md border border-border bg-surface px-4 py-3 text-xs leading-relaxed text-muted">
            This breakdown was generated by an AI model reading{" "}
            {analysis.frames_analyzed} sampled frames. It can be wrong, and it
            is not coaching or medical advice. Check anything that matters with
            a qualified coach.
          </p>
        </>
      ) : job && isJobActive(job.status) ? (
        <PendingState job={job} />
      ) : job?.status === "failed" ? (
        <FailedState job={job} />
      ) : (
        <div className="rounded-lg border border-dashed border-border p-10 text-center">
          <p className="mb-1 text-foreground">No analysis for this clip.</p>
          <p className="text-sm text-muted">
            The job may have been canceled. Upload the clip again to retry.
          </p>
        </div>
      )}
    </div>
  );
}

function PendingState({ job }: { job: AnalysisJob }) {
  return (
    <div className="rounded-lg border border-border bg-surface p-8 text-center">
      <p className="display mb-2 text-2xl">
        {JOB_STAGE_LABELS[job.status]}
        <span aria-hidden>…</span>
      </p>
      <p className="mb-6 text-sm text-muted">
        {job.stage_detail ?? "Processing in the background."}
      </p>
      <div
        className="mx-auto mb-6 h-1.5 w-full max-w-sm overflow-hidden rounded-full bg-surface-raised"
        role="progressbar"
        aria-valuenow={job.progress}
        aria-valuemin={0}
        aria-valuemax={100}
        aria-label="Analysis progress"
      >
        <div
          className="h-full rounded-full bg-accent transition-all"
          style={{ width: `${Math.max(job.progress, 4)}%` }}
        />
      </div>
      <p className="text-xs text-muted">
        Refresh this page to check again — processing continues without it.
      </p>
    </div>
  );
}

function FailedState({ job }: { job: AnalysisJob }) {
  return (
    <div className="rounded-lg border border-accent/40 bg-accent-soft p-8">
      <p className="display mb-2 text-2xl">Analysis failed</p>
      <p className="mb-5 text-sm leading-relaxed text-foreground">
        {job.error ?? "Unknown error."}
      </p>
      <p className="mb-6 text-xs text-muted">
        Attempt {job.attempts} of {job.max_attempts}.
      </p>
      <Link
        href="/upload"
        className="inline-block rounded-md bg-accent px-4 py-2 text-sm font-medium text-white transition-opacity hover:opacity-90"
      >
        Try another clip
      </Link>
    </div>
  );
}
